import gcard1 from '../../assets/gallerycard1.png';
import gcard2 from '../../assets/gallerycard2.png';
import gcard3 from '../../assets/gallerycard3.png';
import gcard4 from '../../assets/gallerycard4.png';

 const GalleryCardData = [
    {
        id : "001",
        img : gcard1,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "Human",
        special: "Human",
        clothing:["red","blue"],
        head:["Human",],
        hand:"Human",
        neck:"Human",
        face:"Human",
        eyes:"Human",
        ears:"Human",
        mouth:"Human",
        background:"Blue",

    },
    {
        id : "002",
        img : gcard2,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "003",
        img : gcard3,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "004",
        img : gcard4,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "005",
        img : gcard1,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "006",
        img : gcard2,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "007",
        img : gcard3,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "008",
        img : gcard4,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "009",
        img : gcard1,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "0010",
        img : gcard2,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "0011",
        img : gcard3,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
    {
        id : "0012",
        img : gcard4,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : "",
        special: "",
        clothing:[],
        head:[],
        hand:"",
        neck:"",
        face:"",
        eyes:"",
        ears:"",
        mouth:"",
        background:"",

    },
]

export default GalleryCardData;