import gcard1 from '../../assets/gallerycard1.png';
import gcard2 from '../../assets/gallerycard2.png';
import gcard3 from '../../assets/gallerycard3.png';
import gcard4 from '../../assets/gallerycard4.png';

 const GalleryCardData = [
    {
        id : "001",
        img : gcard1,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "002",
        img : gcard2,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["red"],
        special: ["style", "myst"],
        clothing:["blue", "relaxed"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark"],

    },
    {
        id : "003",
        img : gcard3,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow"],
        clothing:["blue",  "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:[ "Blue"],

    },
    {
        id : "004",
        img : gcard4,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "005",
        img : gcard1,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:[ "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "006",
        img : gcard2,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:[ "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "007",
        img : gcard3,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "008",
        img : gcard4,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "009",
        img : gcard1,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "0010",
        img : gcard2,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "0011",
        img : gcard3,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
    {
        id : "0012",
        img : gcard4,
        desc : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisi mauris venenatis est auctor eu. Tellus diam eu ac, nec tortor porta lobortis aliquet.",
        style : ["blue"],
        special: ["style", "glow", "myst"],
        clothing:["blue", "relaxed", "suit"],
        head:["messy", "bun"],
        hand:["krabi"],
        neck:["plain"],
        face:["style"],
        eyes:["calm"],
        ears:["human"],
        mouth:["vapor"],
        background:["dark", "Blue"],

    },
]

export default GalleryCardData;